# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: A Xeus-cling based Jupyter book
author: The ESE team
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    

# Information about where the book exists on the web
repository:
  url: https://github.com/jrper/xeus-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: classic
  binderhub_url: https://mybinder.org
  thebe: true

repository:
  url: https://github.com/jrper/xeus-book
  path_to_book: docs                        # The name of the repository on the web
  branch: main                   # The branch on which your textbook is hosted.
