name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/workflows/back_end.yml'
      - 'environment.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'

# This checks the code out, builds the book, and pushes it to `gh-pages`
jobs:
  checkout-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Build the book
    - name: Build the book
      uses: docker://ghcr.io/jrper/xeus-book:main
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
